// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chatMessages.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMeetingMessagesByID = `-- name: GetMeetingMessagesByID :many
SELECT message_id, internal_meeting_id, internal_user_id, chat_id, message_content, send_time
FROM chat_messages
WHERE internal_meeting_id = $1
`

func (q *Queries) GetMeetingMessagesByID(ctx context.Context, internalMeetingID string) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getMeetingMessagesByID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChatMessage
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.MessageID,
			&i.InternalMeetingID,
			&i.InternalUserID,
			&i.ChatID,
			&i.MessageContent,
			&i.SendTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatMessageToMeetingByID = `-- name: InsertChatMessageToMeetingByID :exec
INSERT INTO chat_messages (internal_meeting_id, internal_user_id, chat_id, message_content, send_time)
VALUES ($1, $2, $3, $4, $5)
`

type InsertChatMessageToMeetingByIDParams struct {
	InternalMeetingID string
	InternalUserID    string
	ChatID            string
	MessageContent    string
	SendTime          pgtype.Timestamp
}

func (q *Queries) InsertChatMessageToMeetingByID(ctx context.Context, arg InsertChatMessageToMeetingByIDParams) error {
	_, err := q.db.Exec(ctx, insertChatMessageToMeetingByID,
		arg.InternalMeetingID,
		arg.InternalUserID,
		arg.ChatID,
		arg.MessageContent,
		arg.SendTime,
	)
	return err
}
