// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: meetingEvents.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMeetingEventsByInternalMeetingID = `-- name: GetMeetingEventsByInternalMeetingID :many
SELECT event_id, internal_meeting_id, event_type, event_timestamp
FROM meeting_events
WHERE internal_meeting_id = $1
`

func (q *Queries) GetMeetingEventsByInternalMeetingID(ctx context.Context, internalMeetingID string) ([]MeetingEvent, error) {
	rows, err := q.db.Query(ctx, getMeetingEventsByInternalMeetingID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetingEvent
	for rows.Next() {
		var i MeetingEvent
		if err := rows.Scan(
			&i.EventID,
			&i.InternalMeetingID,
			&i.EventType,
			&i.EventTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMeetingEventForID = `-- name: InsertMeetingEventForID :exec
INSERT INTO meeting_events (internal_meeting_id, event_type, event_timestamp)
VALUES ($1, $2, $3)
`

type InsertMeetingEventForIDParams struct {
	InternalMeetingID string
	EventType         string
	EventTimestamp    pgtype.Timestamp
}

func (q *Queries) InsertMeetingEventForID(ctx context.Context, arg InsertMeetingEventForIDParams) error {
	_, err := q.db.Exec(ctx, insertMeetingEventForID, arg.InternalMeetingID, arg.EventType, arg.EventTimestamp)
	return err
}
