// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getActiveUserCountInMeetingByID = `-- name: GetActiveUserCountInMeetingByID :one
SELECT count(internal_user_id)
FROM users
WHERE internal_user_id IN (SELECT DISTINCT internal_user_id
                           FROM user_events
                           WHERE internal_meeting_id = $1
                             AND leave_timestamp IS NULL)
`

func (q *Queries) GetActiveUserCountInMeetingByID(ctx context.Context, internalMeetingID string) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveUserCountInMeetingByID, internalMeetingID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPresenterUserByMeetingID = `-- name: GetPresenterUserByMeetingID :one
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp, gdpr_name
FROM users
WHERE internal_user_id = (SELECT user_events.internal_user_id
                          FROM user_events
                          WHERE internal_meeting_id = $1
                            AND user_events.event_type = 'user-presenter-assigned'
                          ORDER BY event_timestamp DESC
                          LIMIT 1)
`

func (q *Queries) GetPresenterUserByMeetingID(ctx context.Context, internalMeetingID string) (User, error) {
	row := q.db.QueryRow(ctx, getPresenterUserByMeetingID, internalMeetingID)
	var i User
	err := row.Scan(
		&i.InternalUserID,
		&i.ExternalUserID,
		&i.Name,
		&i.Role,
		&i.IsGuest,
		&i.JoinTimestamp,
		&i.LeaveTimestamp,
		&i.GdprName,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp, gdpr_name
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, internalUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, internalUserID)
	var i User
	err := row.Scan(
		&i.InternalUserID,
		&i.ExternalUserID,
		&i.Name,
		&i.Role,
		&i.IsGuest,
		&i.JoinTimestamp,
		&i.LeaveTimestamp,
		&i.GdprName,
	)
	return i, err
}

const getUserCountBetweenDates = `-- name: GetUserCountBetweenDates :one
SELECT COUNT(*)
FROM users
WHERE join_timestamp BETWEEN $1 AND $2
`

type GetUserCountBetweenDatesParams struct {
	JoinTimestamp   pgtype.Timestamp
	JoinTimestamp_2 pgtype.Timestamp
}

func (q *Queries) GetUserCountBetweenDates(ctx context.Context, arg GetUserCountBetweenDatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCountBetweenDates, arg.JoinTimestamp, arg.JoinTimestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCountInMeetingByInternalID = `-- name: GetUserCountInMeetingByInternalID :one
SELECT count(internal_user_id) AS userCount
FROM users
WHERE internal_user_id IN (SELECT DISTINCT internal_user_id FROM user_events WHERE internal_meeting_id = $1)
`

func (q *Queries) GetUserCountInMeetingByInternalID(ctx context.Context, internalMeetingID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCountInMeetingByInternalID, internalMeetingID)
	var usercount int64
	err := row.Scan(&usercount)
	return usercount, err
}

const getUserEventsState = `-- name: GetUserEventsState :many
SELECT event_type, MAX(event_timestamp) as latest_timestamp
FROM user_events
WHERE internal_user_id = $1
GROUP BY event_type ORDER BY latest_timestamp
`

type GetUserEventsStateRow struct {
	EventType       string
	LatestTimestamp interface{}
}

func (q *Queries) GetUserEventsState(ctx context.Context, internalUserID string) ([]GetUserEventsStateRow, error) {
	rows, err := q.db.Query(ctx, getUserEventsState, internalUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEventsStateRow
	for rows.Next() {
		var i GetUserEventsStateRow
		if err := rows.Scan(&i.EventType, &i.LatestTimestamp); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserExistsByID = `-- name: GetUserExistsByID :one
SELECT TRUE
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserExistsByID(ctx context.Context, internalUserID string) (bool, error) {
	row := q.db.QueryRow(ctx, getUserExistsByID, internalUserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getUsersInMeetingByID = `-- name: GetUsersInMeetingByID :many
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp, gdpr_name
FROM users
WHERE internal_user_id IN (SELECT DISTINCT internal_user_id
                           FROM user_events
                           WHERE internal_meeting_id = $1)
`

func (q *Queries) GetUsersInMeetingByID(ctx context.Context, internalMeetingID string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInMeetingByID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.InternalUserID,
			&i.ExternalUserID,
			&i.Name,
			&i.Role,
			&i.IsGuest,
			&i.JoinTimestamp,
			&i.LeaveTimestamp,
			&i.GdprName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInMeetingByInternalID = `-- name: GetUsersInMeetingByInternalID :many
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp, gdpr_name
FROM users
WHERE internal_user_id IN (SELECT DISTINCT internal_user_id FROM user_events WHERE internal_meeting_id = $1)
`

func (q *Queries) GetUsersInMeetingByInternalID(ctx context.Context, internalMeetingID string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInMeetingByInternalID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.InternalUserID,
			&i.ExternalUserID,
			&i.Name,
			&i.Role,
			&i.IsGuest,
			&i.JoinTimestamp,
			&i.LeaveTimestamp,
			&i.GdprName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoJoinedBetween = `-- name: GetUsersWhoJoinedBetween :many
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp, gdpr_name
FROM users
WHERE join_timestamp BETWEEN $1 AND $2
`

type GetUsersWhoJoinedBetweenParams struct {
	JoinTimestamp   pgtype.Timestamp
	JoinTimestamp_2 pgtype.Timestamp
}

func (q *Queries) GetUsersWhoJoinedBetween(ctx context.Context, arg GetUsersWhoJoinedBetweenParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWhoJoinedBetween, arg.JoinTimestamp, arg.JoinTimestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.InternalUserID,
			&i.ExternalUserID,
			&i.Name,
			&i.Role,
			&i.IsGuest,
			&i.JoinTimestamp,
			&i.LeaveTimestamp,
			&i.GdprName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (internal_user_id, external_user_id, name, gdpr_name, role, is_guest)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertUserParams struct {
	InternalUserID string
	ExternalUserID string
	Name           string
	GdprName       string
	Role           string
	IsGuest        pgtype.Bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.InternalUserID,
		arg.ExternalUserID,
		arg.Name,
		arg.GdprName,
		arg.Role,
		arg.IsGuest,
	)
	return err
}

const leaveAllUsersFromMeetingBySingleTimestamp = `-- name: LeaveAllUsersFromMeetingBySingleTimestamp :exec
UPDATE users SET leave_timestamp = $2 WHERE internal_user_id in (SELECT DISTINCT internal_user_id FROM meeting_events WHERE internal_meeting_id = $1)
`

type LeaveAllUsersFromMeetingBySingleTimestampParams struct {
	InternalMeetingID string
	LeaveTimestamp    pgtype.Timestamp
}

func (q *Queries) LeaveAllUsersFromMeetingBySingleTimestamp(ctx context.Context, arg LeaveAllUsersFromMeetingBySingleTimestampParams) error {
	_, err := q.db.Exec(ctx, leaveAllUsersFromMeetingBySingleTimestamp, arg.InternalMeetingID, arg.LeaveTimestamp)
	return err
}

const leaveUserByID = `-- name: LeaveUserByID :exec
UPDATE users
SET leave_timestamp = $1
WHERE internal_user_id = $2
`

type LeaveUserByIDParams struct {
	LeaveTimestamp pgtype.Timestamp
	InternalUserID string
}

func (q *Queries) LeaveUserByID(ctx context.Context, arg LeaveUserByIDParams) error {
	_, err := q.db.Exec(ctx, leaveUserByID, arg.LeaveTimestamp, arg.InternalUserID)
	return err
}
