/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: bbbServers.sql

package bbbstatus

import (
	"context"
)

const getBBBServerByHostname = `-- name: GetBBBServerByHostname :one
SELECT hostname, api_key, friendly_name, active, api_port, recordings_count FROM bbb_servers WHERE hostname = $1
`

func (q *Queries) GetBBBServerByHostname(ctx context.Context, hostname string) (BbbServer, error) {
	row := q.db.QueryRow(ctx, getBBBServerByHostname, hostname)
	var i BbbServer
	err := row.Scan(
		&i.Hostname,
		&i.ApiKey,
		&i.FriendlyName,
		&i.Active,
		&i.ApiPort,
		&i.RecordingsCount,
	)
	return i, err
}

const getRecordingsCountForAllServer = `-- name: GetRecordingsCountForAllServer :one
SELECT SUM(bbb_servers.recordings_count) AS totalRecordings FROM bbb_servers
`

func (q *Queries) GetRecordingsCountForAllServer(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getRecordingsCountForAllServer)
	var totalrecordings int64
	err := row.Scan(&totalrecordings)
	return totalrecordings, err
}

const incrementRecordingsCountForServer = `-- name: IncrementRecordingsCountForServer :exec
UPDATE bbb_servers SET recordings_count = recordings_count + 1 WHERE hostname = $1
`

func (q *Queries) IncrementRecordingsCountForServer(ctx context.Context, hostname string) error {
	_, err := q.db.Exec(ctx, incrementRecordingsCountForServer, hostname)
	return err
}

const insertBBBServer = `-- name: InsertBBBServer :exec
INSERT INTO bbb_servers (hostname, api_key, friendly_name, active, api_port) VALUES ($1,$2,$3,$4, $5)
`

type InsertBBBServerParams struct {
	Hostname     string
	ApiKey       string
	FriendlyName string
	Active       bool
	ApiPort      string
}

func (q *Queries) InsertBBBServer(ctx context.Context, arg InsertBBBServerParams) error {
	_, err := q.db.Exec(ctx, insertBBBServer,
		arg.Hostname,
		arg.ApiKey,
		arg.FriendlyName,
		arg.Active,
		arg.ApiPort,
	)
	return err
}

const setRecordingsCountForHostname = `-- name: SetRecordingsCountForHostname :exec
UPDATE bbb_servers SET recordings_count = $1 WHERE hostname = $2
`

type SetRecordingsCountForHostnameParams struct {
	RecordingsCount int32
	Hostname        string
}

func (q *Queries) SetRecordingsCountForHostname(ctx context.Context, arg SetRecordingsCountForHostnameParams) error {
	_, err := q.db.Exec(ctx, setRecordingsCountForHostname, arg.RecordingsCount, arg.Hostname)
	return err
}
