/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: meetings.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const endMeetingAtTimestampByID = `-- name: EndMeetingAtTimestampByID :exec
UPDATE meetings
SET meeting_ended = $1
WHERE internal_meeting_id = $2
`

type EndMeetingAtTimestampByIDParams struct {
	MeetingEnded      pgtype.Timestamp
	InternalMeetingID string
}

func (q *Queries) EndMeetingAtTimestampByID(ctx context.Context, arg EndMeetingAtTimestampByIDParams) error {
	_, err := q.db.Exec(ctx, endMeetingAtTimestampByID, arg.MeetingEnded, arg.InternalMeetingID)
	return err
}

const getMeetingById = `-- name: GetMeetingById :one
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended
FROM meetings
WHERE internal_meeting_id = $1
LIMIT 1
`

func (q *Queries) GetMeetingById(ctx context.Context, internalMeetingID string) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingById, internalMeetingID)
	var i Meeting
	err := row.Scan(
		&i.InternalMeetingID,
		&i.ExternalMeetingID,
		&i.Name,
		&i.IsBreakout,
		&i.ParentID,
		&i.CreateTime,
		&i.ModeratorPass,
		&i.ViewerPass,
		&i.Record,
		&i.VoiceConf,
		&i.DialNumber,
		&i.MaxUsers,
		&i.Metadata,
		&i.Bbbhostname,
		&i.ParticipantCount,
		&i.MeetingEnded,
	)
	return i, err
}

const getMeetingCountBetweenDates = `-- name: GetMeetingCountBetweenDates :one
SELECT COUNT(*) FROM meetings WHERE create_time BETWEEN $1 AND $2
`

type GetMeetingCountBetweenDatesParams struct {
	CreateTime   pgtype.Timestamp
	CreateTime_2 pgtype.Timestamp
}

func (q *Queries) GetMeetingCountBetweenDates(ctx context.Context, arg GetMeetingCountBetweenDatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getMeetingCountBetweenDates, arg.CreateTime, arg.CreateTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMeetingExistsByID = `-- name: GetMeetingExistsByID :one
SELECT TRUE
FROM meetings
WHERE internal_meeting_id = $1
LIMIT 1
`

func (q *Queries) GetMeetingExistsByID(ctx context.Context, internalMeetingID string) (bool, error) {
	row := q.db.QueryRow(ctx, getMeetingExistsByID, internalMeetingID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getMeetings = `-- name: GetMeetings :many
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended
FROM meetings
`

func (q *Queries) GetMeetings(ctx context.Context) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, getMeetings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meeting
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.InternalMeetingID,
			&i.ExternalMeetingID,
			&i.Name,
			&i.IsBreakout,
			&i.ParentID,
			&i.CreateTime,
			&i.ModeratorPass,
			&i.ViewerPass,
			&i.Record,
			&i.VoiceConf,
			&i.DialNumber,
			&i.MaxUsers,
			&i.Metadata,
			&i.Bbbhostname,
			&i.ParticipantCount,
			&i.MeetingEnded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeetingsBetweenDates = `-- name: GetMeetingsBetweenDates :many
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended
FROM meetings
WHERE create_time BETWEEN $1 AND $2
`

type GetMeetingsBetweenDatesParams struct {
	CreateTime   pgtype.Timestamp
	CreateTime_2 pgtype.Timestamp
}

func (q *Queries) GetMeetingsBetweenDates(ctx context.Context, arg GetMeetingsBetweenDatesParams) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, getMeetingsBetweenDates, arg.CreateTime, arg.CreateTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meeting
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.InternalMeetingID,
			&i.ExternalMeetingID,
			&i.Name,
			&i.IsBreakout,
			&i.ParentID,
			&i.CreateTime,
			&i.ModeratorPass,
			&i.ViewerPass,
			&i.Record,
			&i.VoiceConf,
			&i.DialNumber,
			&i.MaxUsers,
			&i.Metadata,
			&i.Bbbhostname,
			&i.ParticipantCount,
			&i.MeetingEnded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMeeting = `-- name: InsertMeeting :exec
INSERT INTO meetings (internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time,
                      moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertMeetingParams struct {
	InternalMeetingID string
	ExternalMeetingID string
	Name              string
	IsBreakout        pgtype.Bool
	ParentID          pgtype.Text
	CreateTime        pgtype.Timestamp
	ModeratorPass     string
	ViewerPass        string
	Record            pgtype.Bool
	VoiceConf         pgtype.Text
	DialNumber        pgtype.Text
	MaxUsers          pgtype.Int4
	Metadata          []byte
	Bbbhostname       string
}

func (q *Queries) InsertMeeting(ctx context.Context, arg InsertMeetingParams) error {
	_, err := q.db.Exec(ctx, insertMeeting,
		arg.InternalMeetingID,
		arg.ExternalMeetingID,
		arg.Name,
		arg.IsBreakout,
		arg.ParentID,
		arg.CreateTime,
		arg.ModeratorPass,
		arg.ViewerPass,
		arg.Record,
		arg.VoiceConf,
		arg.DialNumber,
		arg.MaxUsers,
		arg.Metadata,
		arg.Bbbhostname,
	)
	return err
}
