/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: meetingEvents.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMeetingEventsByInternalMeetingID = `-- name: GetMeetingEventsByInternalMeetingID :many
SELECT event_id, internal_meeting_id, event_type, event_timestamp
FROM meeting_events
WHERE internal_meeting_id = $1
`

func (q *Queries) GetMeetingEventsByInternalMeetingID(ctx context.Context, internalMeetingID string) ([]MeetingEvent, error) {
	rows, err := q.db.Query(ctx, getMeetingEventsByInternalMeetingID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MeetingEvent
	for rows.Next() {
		var i MeetingEvent
		if err := rows.Scan(
			&i.EventID,
			&i.InternalMeetingID,
			&i.EventType,
			&i.EventTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMeetingEventForID = `-- name: InsertMeetingEventForID :exec
INSERT INTO meeting_events (internal_meeting_id, event_type, event_timestamp) VALUES ($1, $2, $3)
`

type InsertMeetingEventForIDParams struct {
	InternalMeetingID string
	EventType         string
	EventTimestamp    pgtype.Timestamp
}

func (q *Queries) InsertMeetingEventForID(ctx context.Context, arg InsertMeetingEventForIDParams) error {
	_, err := q.db.Exec(ctx, insertMeetingEventForID, arg.InternalMeetingID, arg.EventType, arg.EventTimestamp)
	return err
}
