/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: meetings.sql

package bbbstatus

import (
	"context"
)

const getMeetingById = `-- name: GetMeetingById :one
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended FROM meetings WHERE internal_meeting_id = $1 LIMIT 1
`

func (q *Queries) GetMeetingById(ctx context.Context, internalMeetingID string) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingById, internalMeetingID)
	var i Meeting
	err := row.Scan(
		&i.InternalMeetingID,
		&i.ExternalMeetingID,
		&i.Name,
		&i.IsBreakout,
		&i.ParentID,
		&i.CreateTime,
		&i.ModeratorPass,
		&i.ViewerPass,
		&i.Record,
		&i.VoiceConf,
		&i.DialNumber,
		&i.MaxUsers,
		&i.Metadata,
		&i.Bbbhostname,
		&i.ParticipantCount,
		&i.MeetingEnded,
	)
	return i, err
}
