/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: meetings.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMeetingById = `-- name: GetMeetingById :one
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended
FROM meetings
WHERE internal_meeting_id = $1
LIMIT 1
`

func (q *Queries) GetMeetingById(ctx context.Context, internalMeetingID string) (Meeting, error) {
	row := q.db.QueryRow(ctx, getMeetingById, internalMeetingID)
	var i Meeting
	err := row.Scan(
		&i.InternalMeetingID,
		&i.ExternalMeetingID,
		&i.Name,
		&i.IsBreakout,
		&i.ParentID,
		&i.CreateTime,
		&i.ModeratorPass,
		&i.ViewerPass,
		&i.Record,
		&i.VoiceConf,
		&i.DialNumber,
		&i.MaxUsers,
		&i.Metadata,
		&i.Bbbhostname,
		&i.ParticipantCount,
		&i.MeetingEnded,
	)
	return i, err
}

const getMeetingExistsByID = `-- name: GetMeetingExistsByID :one
SELECT TRUE FROM meetings WHERE internal_meeting_id = $1 LIMIT 1
`

func (q *Queries) GetMeetingExistsByID(ctx context.Context, internalMeetingID string) (bool, error) {
	row := q.db.QueryRow(ctx, getMeetingExistsByID, internalMeetingID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getMeetings = `-- name: GetMeetings :many
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended
FROM meetings
`

func (q *Queries) GetMeetings(ctx context.Context) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, getMeetings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meeting
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.InternalMeetingID,
			&i.ExternalMeetingID,
			&i.Name,
			&i.IsBreakout,
			&i.ParentID,
			&i.CreateTime,
			&i.ModeratorPass,
			&i.ViewerPass,
			&i.Record,
			&i.VoiceConf,
			&i.DialNumber,
			&i.MaxUsers,
			&i.Metadata,
			&i.Bbbhostname,
			&i.ParticipantCount,
			&i.MeetingEnded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMeetingsBetweenDates = `-- name: GetMeetingsBetweenDates :many
SELECT internal_meeting_id, external_meeting_id, name, is_breakout, parent_id, create_time, moderator_pass, viewer_pass, record, voice_conf, dial_number, max_users, metadata, bbbhostname, participant_count, meeting_ended
FROM meetings
WHERE create_time BETWEEN $1 AND $2
`

type GetMeetingsBetweenDatesParams struct {
	CreateTime   pgtype.Timestamp
	CreateTime_2 pgtype.Timestamp
}

func (q *Queries) GetMeetingsBetweenDates(ctx context.Context, arg GetMeetingsBetweenDatesParams) ([]Meeting, error) {
	rows, err := q.db.Query(ctx, getMeetingsBetweenDates, arg.CreateTime, arg.CreateTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meeting
	for rows.Next() {
		var i Meeting
		if err := rows.Scan(
			&i.InternalMeetingID,
			&i.ExternalMeetingID,
			&i.Name,
			&i.IsBreakout,
			&i.ParentID,
			&i.CreateTime,
			&i.ModeratorPass,
			&i.ViewerPass,
			&i.Record,
			&i.VoiceConf,
			&i.DialNumber,
			&i.MaxUsers,
			&i.Metadata,
			&i.Bbbhostname,
			&i.ParticipantCount,
			&i.MeetingEnded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
