// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package bbbstatus

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type MeetingEventType string

const (
	MeetingEventTypeMeetingCreated MeetingEventType = "meeting-created"
	MeetingEventTypeMeetingEnded   MeetingEventType = "meeting-ended"
)

func (e *MeetingEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeetingEventType(s)
	case string:
		*e = MeetingEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for MeetingEventType: %T", src)
	}
	return nil
}

type NullMeetingEventType struct {
	MeetingEventType MeetingEventType
	Valid            bool // Valid is true if MeetingEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeetingEventType) Scan(value interface{}) error {
	if value == nil {
		ns.MeetingEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeetingEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeetingEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeetingEventType), nil
}

type UserEventType string

const (
	UserEventTypeUserJoined             UserEventType = "user-joined"
	UserEventTypeUserLeft               UserEventType = "user-left"
	UserEventTypeUserPresenterAsSigned  UserEventType = "user-presenter-as-signed"
	UserEventTypeUserAudioVoiceEnabled  UserEventType = "user-audio-voice-enabled"
	UserEventTypeUserAudioVoiceDisabled UserEventType = "user-audio-voice-disabled"
	UserEventTypeUserAudioMuted         UserEventType = "user-audio-muted"
	UserEventTypeUserAudioUnmuted       UserEventType = "user-audio-unmuted"
	UserEventTypeUserCamBroadcastStart  UserEventType = "user-cam-broadcast-start"
	UserEventTypeUserCamBroadcastEnd    UserEventType = "user-cam-broadcast-end"
	UserEventTypeUserEmojiChanged       UserEventType = "user-emoji-changed"
	UserEventTypeUserRaiseHandChanged   UserEventType = "user-raise-hand-changed"
)

func (e *UserEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserEventType(s)
	case string:
		*e = UserEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for UserEventType: %T", src)
	}
	return nil
}

type NullUserEventType struct {
	UserEventType UserEventType
	Valid         bool // Valid is true if UserEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserEventType) Scan(value interface{}) error {
	if value == nil {
		ns.UserEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserEventType), nil
}

type BbbServer struct {
	Hostname        string
	ApiKey          string
	FriendlyName    string
	Active          bool
	ApiPort         string
	RecordingsCount int32
}

type ChatMessage struct {
	MessageID         uuid.UUID
	InternalMeetingID string
	InternalUserID    string
	ChatID            string
	MessageContent    string
	SendTime          pgtype.Timestamp
}

type Meeting struct {
	InternalMeetingID string
	ExternalMeetingID string
	Name              string
	IsBreakout        pgtype.Bool
	ParentID          pgtype.Text
	CreateTime        pgtype.Timestamp
	ModeratorPass     string
	ViewerPass        string
	Record            pgtype.Bool
	VoiceConf         pgtype.Text
	DialNumber        pgtype.Text
	MaxUsers          pgtype.Int4
	Metadata          []byte
	Bbbhostname       string
	ParticipantCount  pgtype.Int4
	MeetingEnded      pgtype.Timestamp
}

type MeetingEvent struct {
	EventID           uuid.UUID
	InternalMeetingID string
	EventType         string
	EventTimestamp    pgtype.Timestamp
}

type Poll struct {
	PollID            string
	InternalMeetingID string
	InternalUserID    string
	Question          string
	Answers           string
	CreatedAt         pgtype.Timestamp
}

type PollResponse struct {
	ResponseID     uuid.UUID
	PollID         string
	InternalUserID string
	AnswerIds      string
	ResponseTime   pgtype.Timestamp
}

type User struct {
	InternalUserID string
	ExternalUserID string
	Name           string
	Role           string
	IsGuest        pgtype.Bool
	JoinTimestamp  pgtype.Timestamp
	LeaveTimestamp pgtype.Timestamp
	DsgvoName      string
}

type UserEvent struct {
	EventID           uuid.UUID
	InternalMeetingID string
	InternalUserID    string
	EventType         string
	EventTimestamp    pgtype.Timestamp
}
