// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: polls.sql

package bbbstatus

import (
	"context"
)

const getPollAnswersByPollID = `-- name: GetPollAnswersByPollID :many
SELECT answers
FROM polls
WHERE poll_id = $1
`

func (q *Queries) GetPollAnswersByPollID(ctx context.Context, pollID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPollAnswersByPollID, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var answers string
		if err := rows.Scan(&answers); err != nil {
			return nil, err
		}
		items = append(items, answers)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollResponsesByPollID = `-- name: GetPollResponsesByPollID :many
SELECT response_id, poll_id, internal_user_id, answer_ids, response_time
FROM poll_responses
WHERE poll_id = $1
`

func (q *Queries) GetPollResponsesByPollID(ctx context.Context, pollID string) ([]PollResponse, error) {
	rows, err := q.db.Query(ctx, getPollResponsesByPollID, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PollResponse
	for rows.Next() {
		var i PollResponse
		if err := rows.Scan(
			&i.ResponseID,
			&i.PollID,
			&i.InternalUserID,
			&i.AnswerIds,
			&i.ResponseTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
