/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: polls.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPollAnswersByPollID = `-- name: GetPollAnswersByPollID :many
SELECT answers FROM polls WHERE poll_id = $1
`

func (q *Queries) GetPollAnswersByPollID(ctx context.Context, pollID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getPollAnswersByPollID, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var answers string
		if err := rows.Scan(&answers); err != nil {
			return nil, err
		}
		items = append(items, answers)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPollResponsesByPollID = `-- name: GetPollResponsesByPollID :many
SELECT internal_user_id, answer_ids, response_time FROM poll_responses WHERE poll_id = $1
`

type GetPollResponsesByPollIDRow struct {
	InternalUserID string
	AnswerIds      string
	ResponseTime   pgtype.Timestamp
}

func (q *Queries) GetPollResponsesByPollID(ctx context.Context, pollID string) ([]GetPollResponsesByPollIDRow, error) {
	rows, err := q.db.Query(ctx, getPollResponsesByPollID, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPollResponsesByPollIDRow
	for rows.Next() {
		var i GetPollResponsesByPollIDRow
		if err := rows.Scan(&i.InternalUserID, &i.AnswerIds, &i.ResponseTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
