/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package bbbstatus

import (
	"context"
)

const getUserById = `-- name: GetUserById :one
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, internalUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, internalUserID)
	var i User
	err := row.Scan(
		&i.InternalUserID,
		&i.ExternalUserID,
		&i.Name,
		&i.Role,
		&i.IsGuest,
		&i.JoinTimestamp,
		&i.LeaveTimestamp,
	)
	return i, err
}

const getUserNameById = `-- name: GetUserNameById :one
SELECT name
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserNameById(ctx context.Context, internalUserID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserNameById, internalUserID)
	var name string
	err := row.Scan(&name)
	return name, err
}
