/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPresenterUserByMeetingID = `-- name: GetPresenterUserByMeetingID :one
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp
FROM users
WHERE internal_user_id = (SELECT user_events.internal_user_id
                          FROM user_events
                          WHERE internal_meeting_id = $1
                          ORDER BY event_timestamp DESC
                          LIMIT 1)
`

func (q *Queries) GetPresenterUserByMeetingID(ctx context.Context, internalMeetingID string) (User, error) {
	row := q.db.QueryRow(ctx, getPresenterUserByMeetingID, internalMeetingID)
	var i User
	err := row.Scan(
		&i.InternalUserID,
		&i.ExternalUserID,
		&i.Name,
		&i.Role,
		&i.IsGuest,
		&i.JoinTimestamp,
		&i.LeaveTimestamp,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserById(ctx context.Context, internalUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserById, internalUserID)
	var i User
	err := row.Scan(
		&i.InternalUserID,
		&i.ExternalUserID,
		&i.Name,
		&i.Role,
		&i.IsGuest,
		&i.JoinTimestamp,
		&i.LeaveTimestamp,
	)
	return i, err
}

const getUserCountBetweenDates = `-- name: GetUserCountBetweenDates :one
SELECT COUNT(*)
FROM users
WHERE join_timestamp BETWEEN $1 AND $2
`

type GetUserCountBetweenDatesParams struct {
	JoinTimestamp   pgtype.Timestamp
	JoinTimestamp_2 pgtype.Timestamp
}

func (q *Queries) GetUserCountBetweenDates(ctx context.Context, arg GetUserCountBetweenDatesParams) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCountBetweenDates, arg.JoinTimestamp, arg.JoinTimestamp_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUserCountInMeetingByInternalID = `-- name: GetUserCountInMeetingByInternalID :one
SELECT count(internal_user_id) AS userCount
FROM users
WHERE internal_user_id IN (SELECT DISTINCT internal_user_id FROM user_events WHERE internal_meeting_id = $1)
`

func (q *Queries) GetUserCountInMeetingByInternalID(ctx context.Context, internalMeetingID string) (int64, error) {
	row := q.db.QueryRow(ctx, getUserCountInMeetingByInternalID, internalMeetingID)
	var usercount int64
	err := row.Scan(&usercount)
	return usercount, err
}

const getUserExistsByID = `-- name: GetUserExistsByID :one
SELECT TRUE
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserExistsByID(ctx context.Context, internalUserID string) (bool, error) {
	row := q.db.QueryRow(ctx, getUserExistsByID, internalUserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getUserNameById = `-- name: GetUserNameById :one
SELECT name
FROM users
WHERE internal_user_id = $1
`

func (q *Queries) GetUserNameById(ctx context.Context, internalUserID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserNameById, internalUserID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getUsersInMeetingByInternalID = `-- name: GetUsersInMeetingByInternalID :many
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp
FROM users
WHERE internal_user_id IN (SELECT DISTINCT internal_user_id FROM user_events WHERE internal_meeting_id = $1)
`

func (q *Queries) GetUsersInMeetingByInternalID(ctx context.Context, internalMeetingID string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersInMeetingByInternalID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.InternalUserID,
			&i.ExternalUserID,
			&i.Name,
			&i.Role,
			&i.IsGuest,
			&i.JoinTimestamp,
			&i.LeaveTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersWhoJoinedBetween = `-- name: GetUsersWhoJoinedBetween :many
SELECT internal_user_id, external_user_id, name, role, is_guest, join_timestamp, leave_timestamp
FROM users
WHERE join_timestamp BETWEEN $1 AND $2
`

type GetUsersWhoJoinedBetweenParams struct {
	JoinTimestamp   pgtype.Timestamp
	JoinTimestamp_2 pgtype.Timestamp
}

func (q *Queries) GetUsersWhoJoinedBetween(ctx context.Context, arg GetUsersWhoJoinedBetweenParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsersWhoJoinedBetween, arg.JoinTimestamp, arg.JoinTimestamp_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.InternalUserID,
			&i.ExternalUserID,
			&i.Name,
			&i.Role,
			&i.IsGuest,
			&i.JoinTimestamp,
			&i.LeaveTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUser = `-- name: InsertUser :exec
INSERT INTO users (internal_user_id, external_user_id, name, role, is_guest)
VALUES ($1, $2, $3, $4, $5)
`

type InsertUserParams struct {
	InternalUserID string
	ExternalUserID string
	Name           string
	Role           string
	IsGuest        pgtype.Bool
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.Exec(ctx, insertUser,
		arg.InternalUserID,
		arg.ExternalUserID,
		arg.Name,
		arg.Role,
		arg.IsGuest,
	)
	return err
}

const leaveUserByID = `-- name: LeaveUserByID :exec
UPDATE users
SET leave_timestamp = $1
WHERE internal_user_id = $2
`

type LeaveUserByIDParams struct {
	LeaveTimestamp pgtype.Timestamp
	InternalUserID string
}

func (q *Queries) LeaveUserByID(ctx context.Context, arg LeaveUserByIDParams) error {
	_, err := q.db.Exec(ctx, leaveUserByID, arg.LeaveTimestamp, arg.InternalUserID)
	return err
}

const setUserNameByID = `-- name: SetUserNameByID :exec
UPDATE users
set name = $1
where internal_user_id = $2
`

type SetUserNameByIDParams struct {
	Name           string
	InternalUserID string
}

func (q *Queries) SetUserNameByID(ctx context.Context, arg SetUserNameByIDParams) error {
	_, err := q.db.Exec(ctx, setUserNameByID, arg.Name, arg.InternalUserID)
	return err
}
