/*
 * Copyright 2025 Samuel Kemper
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: userEvents.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserEventsByMeetingID = `-- name: GetUserEventsByMeetingID :many
SELECT event_timestamp, internal_user_id, event_type FROM user_events WHERE internal_meeting_id = $1
`

type GetUserEventsByMeetingIDRow struct {
	EventTimestamp pgtype.Timestamp
	InternalUserID string
	EventType      string
}

func (q *Queries) GetUserEventsByMeetingID(ctx context.Context, internalMeetingID string) ([]GetUserEventsByMeetingIDRow, error) {
	rows, err := q.db.Query(ctx, getUserEventsByMeetingID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEventsByMeetingIDRow
	for rows.Next() {
		var i GetUserEventsByMeetingIDRow
		if err := rows.Scan(&i.EventTimestamp, &i.InternalUserID, &i.EventType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDsFromMeetingByMeetingID = `-- name: GetUserIDsFromMeetingByMeetingID :many
SELECT DISTINCT internal_user_id FROM user_events WHERE internal_meeting_id = $1
`

func (q *Queries) GetUserIDsFromMeetingByMeetingID(ctx context.Context, internalMeetingID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserIDsFromMeetingByMeetingID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var internal_user_id string
		if err := rows.Scan(&internal_user_id); err != nil {
			return nil, err
		}
		items = append(items, internal_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
