// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: userEvents.sql

package bbbstatus

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserEventsByMeetingID = `-- name: GetUserEventsByMeetingID :many
SELECT event_id, internal_meeting_id, internal_user_id, event_type, event_timestamp
FROM user_events
WHERE internal_meeting_id = $1
`

func (q *Queries) GetUserEventsByMeetingID(ctx context.Context, internalMeetingID string) ([]UserEvent, error) {
	rows, err := q.db.Query(ctx, getUserEventsByMeetingID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserEvent
	for rows.Next() {
		var i UserEvent
		if err := rows.Scan(
			&i.EventID,
			&i.InternalMeetingID,
			&i.InternalUserID,
			&i.EventType,
			&i.EventTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserIDsFromMeetingByMeetingID = `-- name: GetUserIDsFromMeetingByMeetingID :many
SELECT DISTINCT internal_user_id
FROM user_events
WHERE internal_meeting_id = $1
`

func (q *Queries) GetUserIDsFromMeetingByMeetingID(ctx context.Context, internalMeetingID string) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserIDsFromMeetingByMeetingID, internalMeetingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var internal_user_id string
		if err := rows.Scan(&internal_user_id); err != nil {
			return nil, err
		}
		items = append(items, internal_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserEvent = `-- name: InsertUserEvent :exec
INSERT INTO user_events (internal_meeting_id, internal_user_id, event_type, event_timestamp)
VALUES ($1, $2, $3, $4)
`

type InsertUserEventParams struct {
	InternalMeetingID string
	InternalUserID    string
	EventType         string
	EventTimestamp    pgtype.Timestamp
}

func (q *Queries) InsertUserEvent(ctx context.Context, arg InsertUserEventParams) error {
	_, err := q.db.Exec(ctx, insertUserEvent,
		arg.InternalMeetingID,
		arg.InternalUserID,
		arg.EventType,
		arg.EventTimestamp,
	)
	return err
}
